export const CREATE_STORE = "CREATE_BUSINESS_STORE";
export const CREATE_PRODUCTS_STORE = "CREATE_PRODUCTS_BY_STORE";
export const CREATE_PRODUCT_CATEGORIES = "CREATE_PRODUCT_CATEGORIES_BY_STORE";
export const GET_BUSINESS_STORE = "GET_BUSINESS_STORE";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_ORDERS_BY_BUSINESS_KEY_WORDS= "GET_ORDERS_BY_BUSINESS_KEY_WORDS";
export const SET_ORDER_STATUS= "SET_ORDER_STATUS";

