export const CREATE_BUSINESS_PER_USER="CREATE_BUSINESS_PER_USER";
export const GET_BUSINESS_BY_KEY_WORD="GET_BUSINESS_BY_KEY_WORD"
export const ADD_CLICK_TO_BUSINESS="ADD_CLICK_TO_BUSINESS"
export const CHECK_KEY_WORDS="CHECK_KEY_WORDS"
export const ADD_USER_GALERY_OF_BUSINESS="ADD_USER_GALERY_OF_BUSINESS"
export const ALL_NAMES_OF_BUSINESSES="ALL_NAMES_OF_BUSINESSES"
export const GET_PROMOTED_BUSINESSES="GET_PROMOTED_BUSINESSES"
export const DELETE_FAVORAITS="DELETE_FAVORAITS"
export const GET_ALL_FAVORAITS="GET_ALL_FAVORAITS"
export const ADD_FAVORITES_TO_BUSINESS="ADD_FAVORITES_TO_BUSINESS"
export const SEND_MAIL_TO_CONTACT="SEND_MAIL_TO_CONTACT"
export const SEND_SMS_TO_CONTACT="SEND_SMS_TO_CONTACT"
export const GET_BUSINESS_RECOMMENDATIONS="GET_BUSINESS_RECOMMENDATIONS"
// export const ADD_FAVORAITS_TO_BUSINESS="ADD_FAVORAITS_TO_BUSINESS"




