export const GET_PLACE_ID_OF_BUSINESS="GET_PLACE_ID_OF_BUSINESS";
export const GET_PLACES_BY_SEARCH="GET_PLACES_BY_SEARCH";
export const  GET_DETAILS_BY_PLACE_ID="GET_DETAILS_BY_PLACE_ID";
export const  GET_PHOTOS_BY_PLACE_ID="GET_PHOTOS_BY_PLACE_ID";
export const  GET_PLACES_BY_LOCATION="GET_PLACES_BY_LOCATION";